# Generated by Django 4.2.9 on 2024-01-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('slug', models.CharField(blank=True, default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.CharField(blank=True, default='', max_length=200)),
                ('end_date', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('slug', models.CharField(blank=True, default='', max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id_num', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('jp_rateups', models.ManyToManyField(related_name='jp_rateups', to='banners_app.banner')),
                ('na_rateups', models.ManyToManyField(related_name='na_rateups', to='banners_app.banner')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners_app.event'),
        ),
    ]
